import{a as S,i as h,S as I}from"./assets/vendor-D0cagnvz.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const B="47906037-2c0a065ebc1b1a12e8c8fed40",H="https://pixabay.com/api/";async function m(t,n=1){const i=`${H}?key=${B}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`,e=await S.get(i);if(e.status!==200)throw new Error("Failed to fetch images.");return e.data}const d=document.getElementById("gallery"),g=document.getElementById("loader");function p(t,n=!1){const o=t.map(({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:v,comments:$,downloads:P})=>`
      <a href="${e}" class="gallery-item">
        <img src="${i}" alt="${r}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${s}</p>
          <p><b>Views:</b> ${v}</p>
          <p><b>Comments:</b> ${$}</p>
          <p><b>Downloads:</b> ${P}</p>
        </div>
      </a>
    `).join("");n?d.insertAdjacentHTML("beforeend",o):d.innerHTML=o}function q(){d.innerHTML=""}function y(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}function u(t){h.error({title:"Error",message:t})}function L(t){h.warning({title:"Warning",message:t})}const x=document.getElementById("search-form"),O=document.getElementById("search-input"),a=document.createElement("button");a.textContent="Load more";a.className="hidden";a.id="load-more";document.querySelector(".container").appendChild(a);let l,c=1,f="",w=0;x.addEventListener("submit",async t=>{t.preventDefault();const n=O.value.trim();if(!n){u("Search field cannot be empty!");return}f=n,c=1,q(),a.classList.add("hidden"),y();try{const o=await m(f,c);if(w=o.totalHits,o.hits.length===0){L("Sorry, there are no images matching your search query. Please try again!");return}p(o.hits),E(),o.totalHits>15&&a.classList.remove("hidden")}catch{u("Something went wrong. Please try again later.")}finally{b()}});a.addEventListener("click",async()=>{c+=1,y();try{const t=await m(f,c);p(t.hits,!0),E();const{height:n}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),c*15>=w&&(a.classList.add("hidden"),L("We're sorry, but you've reached the end of search results."))}catch{u("Something went wrong. Please try again later.")}finally{b()}});function E(){l?l.refresh():l=new I(".gallery a")}
//# sourceMappingURL=index.js.map
